config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users

  resources :courses do
    resources :lessons
  end

  resources :checkouts , only: [:create]

  post "webhooks/stripe", to: "webhooks#stripe"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :courses

end

app/models/course.rb
class Course < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  has_many :lessons
  has_and_belongs_to_many :categories
  has_many :course_users

  def first_lesson
    self.lessons.order(:position).first
  end

  def next_lesson(current_user)
    if current_user.blank?
      return self.lessons.order(:position).first
    end

    completed_lessons = current_user.lesson_users.includes(:lesson).where(completed: true).where(lessons: { course_id: self.id})
    started_lessons = current_user.lesson_users.includes(:lesson).where(completed: false).where(lesson: { course_id: self.id}).order(:position)

    if started_lessons.any?
      return started_lessons.first.lesson
    end

    lessons = self.lessons.where.not(id: completed_lessons.pluck(:lesson_id)).order(:position)
    if lessons.any?
      lessons.first
    else
      return self.lessons.order(:position).first
    end
  end
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_one_attached :video do |attachable|
    attachable.variant :thumb, resize_to_limit: [500,500]
  end

  belongs_to :course
  has_many :lesson_users, dependent: :destroy

  def next_lesson
    course.lessons.where("position > ?", position).order(:position).first
  end

  def previous_lesson
    course.lessons.where("position < ?", position).order(:position).last
  end
end

app/models/lesson_user.rb
class LessonUser < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { learner: 0, admin: 1 }

  has_many :lesson_users
  has_many :course_users
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action: authenticate_user!
  before_action :authorize_admin!

  private

  def authorize_admin!
    redirect_to root_path, alert: "Access denied." unless current_user&.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  stripe_secret_key = Rails.application.credentials.dig(:stripe, :secret_key)
  Stripe.api_key = stripe_secret_key

  def create
    course = Course.find(params[:course_id])

    session = Stripe::Checkout::Session.create(
      mode: "payment",
      line_items: [{
        price: course.stripe_price_id,
        quantity: 1
      }],
      success_url: request.base_url + "/courses/#{course.id}",
      cancel_url: request.base_url + "/courses/#{course.id}",
      # automatic_tax: { enabled: true },
      customer_email: current_user.email,
      metadata: {
        course_id: course.id
      } 
    )

    redirect_to session.url, allow_other_host: true
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show]

  def index
    @courses = Course.all
    @user_started_courses = current_user&.lesson_users&.joins(:lesson)&.pluck(:course_id)&.uniq
    if @user_started_courses.present?
      @user_course_progresses = @user_started_courses.map do |course_id|
        course_lessons = Course.find(course_id).lessons.count
        completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true, lesson: { course: course_id })&.count
        { course_id: course_id, completed_percentage: (completed_lessons.to_f / course_lessons.to_f * 100).to_i }
      end
    end
  end

  def show
    @completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true, lesson: { course_id: @course.id })&.pluck(:lesson_id)
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show update ]
  before_action :set_course
  before_action :check_paid

  # GET /lessons/1 or /lessons/1.json
  def show
    @completed_lessons = current_user.lesson_users.where(completed:true).pluck(:lesson_id)
    @course = @lesson.course
    @paid_for_course = current_user.course_users.where(course: @course).exists?
    puts "paid_for_course: #{@paid_for_course}"
  end

  def update
    @lesson_user = LessonUser.find_or_create_by(user: current_user, lesson: @lesson)
    @lesson_user.update!(completed: true)
    next_lesson = @course.lessons.where("position > ?", @lesson.position).order(:position).first
    if next_lesson
      redirect_to course_lesson_path(@course, next_lesson)
    else
      redirect_to course_path(@course), notice: "You've completed the course"
    end
  end

  private
    def set_course
      @course = Course.find(params[:course_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def check_paid
      if @lesson.paid && !current_user.course_users.where(course_id: params[:course_id]).exists?
        if @lesson.previous_lesson
          redirect_to course_lesson_path(@course, @lesson.previous_lesson), notice: "You must purchase the full course to access the next lesson"
        else
          redirect_to course_path(@course), notice: "You must purchase the full course to access the next lesson"
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action: authenticate_user!
  before_action :authorize_admin!

end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_forgery_protection

  def stripe
    stripe_secret_key = Rails.application.credentials.dig(:stripe, :secret_key)
    Stripe.api_key = stripe_secret_key
    payload = request.body.read
    sig_header = request.env['HTTP_STRIPE_SIGNATURE']
    endpoint_secret = Rails.application.credentials.dig(:stripe, :webhook_secret)
    event = nil

    begin
      event = Stripe::Webhook.construct_event(payload, sig_header, endpoint_secret)
    rescue JSON::ParserError => e
      status 400
      return
    rescue Stripe::SignatureVerificationError => e
      puts "Webhook signature verification failed."
      status 400
      return
    end

    case event.type
    when "checkout.session.completed"
      session = event.data.object

      full_session = Stripe::Checkout::Session.retrieve({
        id: session.id,
        expand: ['line_items'],
      })

      line_items = full_session.line_items
      puts "session: #{session}"
      puts "line_items: #{line_items}"
      course_id = session.metadata.course_id
      course = Course.find(course_id)
      user = User.find_by!(email: session.customer_email)

      CourseUser.create!(course: course, user: user)
    else
      puts "Unhandled event type: #{event.type}"
    end

    render json: { message: 'success' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>" class="max-w-sm rounded-b overflow-hidden shadow-lg hover:bg-voodoo-100">
  <%= link_to course, class: "flex flex-col h-full" do %>
    <% if course.image.present? %>
      <%= image_tag course.image, class: "w-full rounded-t" %>
    <% else %>
      <%= image_tag("https://placehold.co/300") %>
    <% end %>

    <div class="px-6 py-4 flex flex-col justify-between grow">
      <div>
        <div class="flex items-center justify-between font-bold text-xl mb-2">
          <%= course.title %>
        </div>
        <p class="text-sm font-extralight">Conner Jensen<p>
        <div>
          <p class="text-md font-light"><%= course.paid ? "Premium Content" : "Free" %></p>
        </div>
      </div>
      <% if user_started_courses&.include? course.id %>
        <% user_completed_percentage = user_course_progresses.find{|cp| cp[:course_id] == course.id}[:completed_percentage] %>
        <div class="mt-2 h-4 relative rounded-full overflow-hidden">
          <div class="w-full h-full bg-gray-200 absolute"></div>
          <% if user_completed_percentage == 100 %>
            <div class="h-full bg-green-500 absolute text-white-50 text-center text-xs" style="width:100%">Completed</div>
          <% else %>
            <div class="h-full bg-green-500 absolute text-white-50 text-center text-xs" style="width:<%= user_completed_percentage %>%"><%= user_completed_percentage%>%</div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/courses/_sidebar.html.erb
<div class="flex flex-col lg:pl-6">
  <div class="mt-6 lg:mt-0 flex justify-center items-center w-full">
    <div class="bg-white rounded-lg shadow-lg overflow-hidden w-full">
      <div class="bg-amaranth-500 p-4">
        <h2 class="text-white-50 text-2xl font-bold">Start Learning</h2>
      </div>
      <div class="p-4">
        <% if user_signed_in? %>
          <% if @completed_lessons&.any? %>
            <% if @completed_lessons.count == @course.lessons.count %>
              <p class="text-gray-700 text-base mb-4">
                You have completed this course. Congrats!
              </p>
              <%= link_to "Watch Again", course_lesson_path(@course, @course.first_lesson), class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
            <% else %>
              <p class="text-gray-700 text-base mb-4">
                Continue the course and pick up where you left off.
              </p>
              <%= link_to "Continue Course", course_lesson_path(@course, @course.next_lesson(current_user)), class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
            <% end %>
          <% else %>
            <p class="text-gray-700 text-base mb-4">
            Start the course and begin learning all about the world of web dev.
            </p>
            <%= link_to "Start Course", course_lesson_path(@course, @course.first_lesson), class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
          <% end %> 
        <% else %>
          <p class="text-gray-700 text-base mb-4">
          Sign up for free today and start exploring the endless possibilities.
          </p>
          <%= link_to "Sign Up", new_user_registration_path, class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
        <% end %>
      </div>
    </div>
  </div>
  <% if @course.paid %>
    <div class="mt-6 flex justify-center items-center w-full">
      <div class="bg-white rounded-lg shadow-lg overflow-hidden w-full">
        <div class="bg-amaranth-500 p-4">
          <% if @user_unlocked_course %>
            <h2 class="text-white-50 text-2xl font-bold">You have premium access</h2>
          <% else %>
            <h2 class="text-white-50 text-2xl font-bold">Get more content</h2>
          <% end %>
        </div>
        <div class="p-4">
          <% if user_signed_in? %>
            <% if @user_unlocked_course %>
              <p class="text-gray-700 text-base mb-4">
              You have unlocked this course. Enjoy!
              </p>
              <% if @course.premium_description.present? %>
                <%= @course.premium_description %>
              <% end %>
            <% else %>
              <p class="text-gray-700 text-base mb-4">
              Unlock more content by purchasing the full course.
              </p>
              <% if @course.premium_description.present? %>
                <%= @course.premium_description %>
              <% end %>
              <%= form_tag checkouts_path(@course), method: :post, data: { turbo: false }, class: "mt-4" do %>
                <%= hidden_field_tag :course_id, @course.id %>
                <%= hidden_field_tag :stripeEmail, current_user.email %>
                <%= button_tag "Unlock Full Course", class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
              <% end %>
            <% end %>
          <% else %>
            <p class="text-gray-700 text-base mb-4">
            Sign up for free today and start exploring the endless possibilities.
            </p>
            <%= link_to "Sign Up", new_user_registration_path, class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>
</div>

app/views/courses/index.html.erb
<div class="min-w-full flex flex-wrap justify-center gap-14 pb-6">
  <%= render @courses, { user_started_courses: @user_started_courses, user_course_progresses: @user_course_progresses } %>
</div>

app/views/courses/show.html.erb
<div class="mx-auto w-full flex flex-col lg:flex-row pb-6">
  <div class="mx-auto w-full">
    <% if @course.lessons.any? && @course.lessons.first.video.present? %>
      <%= video_tag @course.lessons.first.video, controls: true, class: "w-full rounded mb-6" %>
    <% end %>

    <div class="border p-6 rounded">
      <div class="flex justify-start items-center flex-wrap w-full mb-2">
        <% @course.categories.each do |category| %>
          <div class="bg-amaranth-100 text-amaranth-800 text-sm font-semibold mt-2 mr-2 px-2.5 py-0.5 rounded"><%= category.name %></div>
        <% end %>
      </div>
      <span><%= @course.lessons.count %> <%= "lesson".pluralize(@course.lessons.count) %> </span>
      <h1 class="text-2xl font-bold"><%= @course.title %></h1>
      <p class="text-gray-500 mt-2"><%= @course.description %></p>
    </div>
  </div>

  <div>
    <%= render "sidebar" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="w-full">
      <%= render "shared/navbar" %>
    </div>
    <main class="container mx-auto mt-6 px-5 flex">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "contents") do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul class="list-disc ml-6">
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lesson.errors[:title].none?, "border-red-400 focus:outline-red-600": lesson.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lesson.errors[:description].none?, "border-red-400 focus:outline-red-600": lesson.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :paid %>
    <%= form.check_box :paid, class: ["block shadow rounded-md border outline-none mt-2 h-5 w-5", {"border-gray-400 focus:outline-blue-600": lesson.errors[:paid].none?, "border-red-400 focus:outline-red-600": lesson.errors[:paid].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :course_id %>
    <%= form.text_field :course_id, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": lesson.errors[:course_id].none?, "border-red-400 focus:outline-red-600": lesson.errors[:course_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= lesson.title %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lesson.description %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Paid:</strong>
    <%= lesson.paid %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Course:</strong>
    <%= lesson.course_id %>
  </p>
</div>

app/views/lessons/_sidebar.html.erb
<div class="w-full">
  <% course.lessons.order(:position).each do |lesson| %>
    <% if lesson.paid && !paid_for_course %>
      <div class="border p-6 hover:bg-gray-200">
        <div>
          <%= icon('fa-solid', 'lock', class: "mr-2 text-gray-600") %><span class="font-light"><%= lesson.title %></span>
        </div>
      </div>
    <% else %>
      <%= link_to course_lesson_path(course, lesson) do %>
        <div class="border p-6 hover:bg-gray-200 <%= @lesson.id == lesson.id ? 'bg-amaranth-100': '' %>">
          <%= completed_lessons&.include?(lesson.id) ? icon('fa-solid', 'check-circle', class: "mr-2 text-green-500") : nil %>
          <span class="font-light"><%= lesson.title %></span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<% content_for :title, "Editing lesson" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Show this lesson", @lesson, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/lessons/index.html.erb
<% content_for :title, "Lessons" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lessons</h1>
    <%= link_to "New lesson", new_lesson_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="lessons" class="min-w-full">
    <% if @lessons.any? %>
      <% @lessons.each do |lesson| %>
        <%= render lesson %>
        <p>
          <%= link_to "Show this lesson", lesson, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No lessons found.</p>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<% content_for :title, "New lesson" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/lessons/show.html.erb
<div class="flex flex-col lg:flex-row-reverse w-full justify-start lg:justify-end pb-6">
  <div>
    <div>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    </div>

    <%= (@lesson.video.present?) ? (video_tag @lesson.video, autoplay: false, controls: true, class: "rounded") : "No video available" %>

    <div class="my-2 border p-4 rounded">
      <h1 class="text-2xl font-semibold"><%= @lesson.title %></h1>
      <p class="text-gray-700"><%= @lesson.description %></p>
    </div>

    <div class="my-6 lg:mb-0">
      <%= link_to "Mark as complete", course_lesson_path(@course, @lesson), data: { 'turbo-method' => :put }, class: "bg-green-500 rounded hover:bg-green-600 text-white-50 px-4 py-2" %>
    </div>
  </div>

  <div class="sidebar_container lg:min-w-60 lg:mr-4 lg:overflow-y-scroll">
    <%= render "lessons/sidebar", course: @course, completed_lessons: @completed_lessons, paid_for_course: @paid_for_course %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="hidden sm:flex w-full justify-center items-center text-gray-700 py-6 px-5">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex">
      <div>
        <%= link_to "Courses", root_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      </div>
    </div>
    <div>
      <%= link_to root_path do %>
        <% image_tag "logo.png", class: "h-12" %> 
      <% end %>
    </div>
    <div class="flex">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { 'turbo_method' => :delete, 'turbo_confirm' => "Are you sure?" }, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
        <%= link_to icon('fa-solid', 'user-circle'), edit_user_registration_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4 text-center" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      <% end %>
    </div>
  </div>
</header>

<header data-controller="navbar" class="bg-amaranth-500 sm:hidden w-full py-4 px-5 text-white-50">
  <div class="flex justify-between items-center">
    <div>
      <%= link_to root_path do %>
        <%= image_tag "logo.png", class: "h-12" %>
      <% end %>
    </div>
    <div class="p-4">
      <button data-action="click->navbar#toggle" id="bars" type="button" class="w-full flex justify-end items-center">
        <%= icon('fa-solid', 'bars') %>
      </button>
      <button data-action="click->navbar#toggle" id="close" type="button" class="hidden w-full flex justify-end items-center">
        <%= icon('fa-solid', 'x') %>
      </button>
    </div>
  </div>

  <div id="mobile-links" class="hidden border-t-2 border-amaranth-400 flex flex-col w-full justify-center items-center">
    <div class="mt-4">
      <%= link_to "Courses", root_path, class: "hover:bg-amaranth-700 rounded py-2 px-4" %>
    </div>

    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, data: { 'turbo_method' => :delete, 'turbo_confirm' => "Are you sure?" }, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      <%= link_to icon('fa-solid', 'user-circle'), edit_user_registration_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4 text-center" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
    <% end %>
  </div>
</header>